import { test, expect } from '@playwright/test'

test('portfolio navigation, project filters and modal details work', async ({ page }) => {
  const errors = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto('/')
  await expect(page.getByRole('heading', { level: 1 })).toContainText('Tecnología que')
  await page.getByRole('button', { name: 'Cloud & infraestructura' }).click()
  await expect(page.getByRole('region', { name: 'Cloud & infraestructura' })).toBeVisible()
  await expect(page.getByRole('region', { name: 'Desarrollo de software' })).toBeHidden()
  await page.getByRole('button', { name: 'Diseño UX/UI', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Ver proyecto Pulse' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Ver proyecto Orbit' })).toHaveCount(0)
  await page.getByRole('button', { name: 'Todos', exact: true }).click()
  await expect(page.locator('.project-card')).toHaveCount(3)
  await page.getByRole('button', { name: 'Ver proyecto Orbit' }).click()
  const dialog = page.getByRole('dialog')
  await expect(dialog.getByRole('heading', { name: 'Orbit.' })).toBeVisible()
  await expect(dialog.getByText('El desafío', { exact: true })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(dialog).toBeHidden()
  await expect(page.getByRole('button', { name: 'Ver proyecto Orbit' })).toBeFocused()
  await page.getByRole('button', { name: 'Ver proyecto Nexo' }).click()
  await page.getByRole('button', { name: 'Quiero construir algo así' }).click()
  await expect(page.getByRole('dialog')).toHaveCount(1)
  await expect(page.getByRole('heading', { name: 'Tu próxima gran idea empieza acá.' })).toBeVisible()
  await page.getByRole('button', { name: 'Cerrar ventana', exact: true }).click()
  expect(errors).toEqual([])
  await page.goto('/')
  await page.evaluate(() => document.fonts.ready)
  await page.screenshot({ path: 'test-results/desktop.png', fullPage: true, animations: 'disabled' })
})

test('contact form validates input and downloads an honest project brief', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Hablemos', exact: true }).click()
  await page.getByLabel('Tu nombre').fill('María García')
  await page.getByLabel('Tu email').fill('maria@example.com')
  await page.getByLabel('Empresa').fill('Empresa de ejemplo')
  await page.getByRole('dialog').getByRole('button', { name: 'Desarrollo', exact: true }).click()
  await page.getByLabel('Contanos tu idea').fill('Quiero una plataforma para organizar los proyectos de mi equipo.')
  await page.getByRole('button', { name: 'Preparar mi proyecto' }).click()
  await expect(page.getByText('Tu brief está listo, María.', { exact: false })).toBeVisible()
  await expect(page.getByText('No se envió ningún mensaje', { exact: false })).toBeVisible()
  const downloadEvent = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Descargar mi brief' }).click()
  const download = await downloadEvent
  expect(download.suggestedFilename()).toBe('blackriver-brief.txt')
  await download.saveAs('test-results/blackriver-brief.txt')
  const fs = await import('node:fs/promises')
  const content = await fs.readFile('test-results/blackriver-brief.txt', 'utf8')
  expect(content).toContain('María García')
  expect(content).toContain('Servicios: Desarrollo')
  expect(content).toContain('organizar los proyectos')
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toBeHidden()
})

test('mobile menu, modals and layout work at narrow widths', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  const toggle = page.getByRole('button', { name: 'Abrir menú' })
  await toggle.click()
  await expect(page.getByRole('navigation', { name: 'Navegación principal' })).toBeVisible()
  await page.getByRole('navigation', { name: 'Navegación principal' }).getByRole('link', { name: 'Proyectos' }).click()
  await expect(toggle).toHaveAttribute('aria-expanded', 'false')
  await expect(page).toHaveURL(/#proyectos$/)
  await page.getByRole('button', { name: 'Ver proyecto Pulse' }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.getByRole('button', { name: 'Cerrar ventana' }).click()
  for (const width of [320, 390, 768, 1024, 1440]) {
    await page.setViewportSize({ width, height: 900 })
    const overflow = await page.evaluate(() => ({
      fits: document.documentElement.scrollWidth <= window.innerWidth,
      elements: [...document.querySelectorAll('body *')].filter((element) => element.getBoundingClientRect().right > window.innerWidth + 1 && getComputedStyle(element).position !== 'absolute').map((element) => `${element.tagName}.${element.className}`).slice(0, 8),
    }))
    expect(overflow.fits, `no horizontal overflow at ${width}px: ${overflow.elements.join(', ')}`).toBe(true)
  }
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await page.evaluate(() => document.fonts.ready)
  await page.screenshot({ path: 'test-results/mobile.png', fullPage: true, animations: 'disabled' })
})
