import { test, expect } from '@playwright/test'

test('admin protects access, follows inquiries and publishes services', async ({ page }) => {
  const errors = []
  page.on('pageerror', e => errors.push(e.message))
  await page.goto('/admin')
  await expect(page.getByRole('button', { name: 'Ingresar' })).toBeVisible()
  await page.getByLabel('Usuario', { exact: true }).fill('admin')
  await page.getByLabel('Contraseña', { exact: true }).fill('incorrecta')
  await page.getByRole('button', { name: 'Ingresar' }).click()
  await expect(page.getByRole('alert')).toContainText('incorrectos')
  await page.getByLabel('Contraseña', { exact: true }).fill('browser-test-password')
  await page.getByRole('button', { name: 'Ingresar' }).click()
  await expect(page.getByRole('button', { name: 'Cerrar sesión' })).toBeVisible()
  const response = await page.request.post('/api/inquiries', { data: { name: 'Cliente de prueba', email: 'cliente@example.com', message: 'Necesito instalar cámaras en el acceso principal.' } })
  expect(response.status()).toBe(201)
  await page.getByRole('button', { name: 'Actualizar', exact: true }).click()
  const inquiry = page.locator('.inquiry-card').filter({ hasText: 'Cliente de prueba' })
  await inquiry.getByRole('combobox', { name: 'Estado', exact: true }).selectOption('En seguimiento')
  await inquiry.getByLabel('Notas internas').fill('Visita técnica pendiente')
  await inquiry.getByRole('button', { name: 'Guardar seguimiento' }).click()
  await expect(inquiry.getByRole('status')).toContainText('Cambios guardados')
  await page.reload()
  await expect(inquiry.getByLabel('Notas internas')).toHaveValue('Visita técnica pendiente')
  await page.getByRole('button', { name: 'Servicios', exact: true }).click()
  await page.getByLabel('Título', { exact: true }).first().fill('Cámaras para tu hogar')
  await page.getByRole('button', { name: 'Guardar y publicar servicios' }).click()
  await expect(page.getByRole('status')).toContainText('Servicios publicados')
  await page.goto('/')
  await expect(page.getByRole('button', { name: 'Cámaras para tu hogar' })).toBeVisible()
  await page.goto('/admin')
  await page.getByRole('button', { name: 'Servicios', exact: true }).click()
  await page.getByLabel('Título', { exact: true }).first().fill('Cámaras web e IP')
  await page.getByRole('button', { name: 'Guardar y publicar servicios' }).click()
  await expect(page.getByRole('status')).toContainText('Servicios publicados')
  await page.setViewportSize({ width: 320, height: 800 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/admin-mobile.png', fullPage: true })
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.screenshot({ path: 'test-results/admin-desktop.png', fullPage: true })
  await page.getByRole('button', { name: 'Cerrar sesión' }).click()
  await expect(page.getByRole('button', { name: 'Ingresar' })).toBeVisible()
  expect((await page.request.get('/api/admin/inquiries')).status()).toBe(401)
  expect(errors).toEqual([])
})
