import { test, expect } from '@playwright/test'

test('clients, orders and hardware can be managed together', async ({ page }) => {
  const errors = []
  page.on('pageerror', e => errors.push(e.message))
  await page.goto('/admin')
  await page.getByLabel('Usuario', { exact: true }).fill('admin')
  await page.getByLabel('Contraseña', { exact: true }).fill('browser-test-password')
  await page.getByRole('button', { name: 'Ingresar' }).click()
  await page.getByRole('button', { name: 'Clientes', exact: true }).click()
  await page.getByRole('button', { name: 'Nuevo cliente' }).click()
  await page.getByLabel('Nombre', { exact: true }).fill('Comercio de prueba')
  await page.getByLabel('Email', { exact: true }).fill('comercio@example.com')
  await page.getByLabel('Teléfono', { exact: true }).fill('1112345678')
  await page.getByRole('button', { name: 'Guardar cliente' }).click()
  await expect(page.getByRole('status')).toContainText('Registro guardado')
  await page.getByRole('button', { name: 'Hardware', exact: true }).click()
  await page.getByRole('button', { name: 'Nuevo equipo' }).click()
  await page.getByLabel('Nombre del equipo', { exact: true }).fill('Cámara de prueba')
  await page.getByLabel('Unidades registradas').fill('3')
  await page.getByLabel('Número de serie (opcional)').fill('BROWSER-CAM-1')
  await page.getByRole('button', { name: 'Guardar equipo' }).click()
  await expect(page.getByRole('status')).toContainText('Registro guardado')
  await page.getByRole('button', { name: 'Encargos', exact: true }).click()
  await page.getByRole('button', { name: 'Nuevo encargo' }).click()
  await page.getByRole('combobox', { name: 'Cliente', exact: true }).selectOption({ label: 'Comercio de prueba' })
  await page.getByLabel('Título del encargo').fill('Instalación de prueba')
  await page.getByLabel('Fecha prevista').fill('2026-10-10')
  await page.getByRole('button', { name: 'Agregar hardware' }).click()
  await page.getByRole('combobox', { name: 'Equipo 1', exact: true }).selectOption({ label: 'Cámara de prueba · 3 disponibles' })
  await page.getByLabel('Cantidad 1', { exact: true }).fill('2')
  await page.getByRole('button', { name: 'Guardar encargo' }).click()
  await expect(page.getByRole('status')).toContainText('Registro guardado')
  const order = page.locator('.management-record').filter({ hasText: 'Instalación de prueba' })
  await expect(order).toContainText('Comercio de prueba')
  await page.reload()
  await page.getByRole('button', { name: 'Encargos', exact: true }).click()
  await expect(order).toContainText('Cámara de prueba · 2 unidad(es)')
  await order.getByRole('button', { name: 'Editar encargo' }).click()
  await page.getByRole('combobox', { name: 'Estado del encargo', exact: true }).selectOption('En curso')
  await page.getByRole('button', { name: 'Guardar encargo' }).click()
  await expect(order).toContainText('En curso')
  await page.setViewportSize({ width: 320, height: 800 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/management-mobile.png', fullPage: true })
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.screenshot({ path: 'test-results/management-desktop.png', fullPage: true })
  await page.getByRole('button', { name: 'Hardware', exact: true }).click()
  const hardware = page.locator('.management-record').filter({ hasText: 'Cámara de prueba' })
  await expect(hardware.locator('.hardware-counts')).toContainText('Disponibles 1')
  await page.getByRole('button', { name: 'Clientes', exact: true }).click()
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: 'Eliminar cliente' }).click()
  await expect(page.getByRole('alert')).toContainText('encargos asociados')
  await page.getByRole('button', { name: 'Encargos', exact: true }).click()
  page.once('dialog', dialog => dialog.accept())
  await order.getByRole('button', { name: 'Eliminar encargo' }).click()
  await expect(page.getByRole('status')).toContainText('Registro eliminado')
  await page.getByRole('button', { name: 'Hardware', exact: true }).click()
  await expect(hardware.locator('.hardware-counts')).toContainText('Disponibles 3')
  page.once('dialog', dialog => dialog.accept())
  await hardware.getByRole('button', { name: 'Eliminar equipo' }).click()
  await expect(page.getByRole('status')).toContainText('Registro eliminado')
  await page.getByRole('button', { name: 'Clientes', exact: true }).click()
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: 'Eliminar cliente' }).click()
  await expect(page.getByRole('status')).toContainText('Registro eliminado')
  expect(errors).toEqual([])
})
