import { test, expect } from '@playwright/test'

test('portfolio navigation, project filters and modal details work', async ({ page }) => {
  const errors = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto('/')
  await expect(page.getByRole('heading', { level: 1 })).toContainText('Rubén Rodríguez')
  await page.getByRole('button', { name: 'Acceso remoto seguro' }).click()
  await expect(page.getByRole('region', { name: 'Acceso remoto seguro' })).toBeVisible()
  await expect(page.getByRole('region', { name: 'Cámaras web e IP' })).toBeHidden()
  await page.getByRole('button', { name: 'Soporte técnico', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Ver proyecto Mantenimiento técnico' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Ver proyecto Monitoreo remoto' })).toHaveCount(0)
  await page.getByRole('button', { name: 'Todos', exact: true }).click()
  await expect(page.locator('.project-card')).toHaveCount(3)
  await page.getByRole('button', { name: 'Ver proyecto Monitoreo remoto' }).click()
  const dialog = page.getByRole('dialog')
  await expect(dialog.getByRole('heading', { name: 'Monitoreo remoto.' })).toBeVisible()
  await expect(dialog.getByText('El desafío', { exact: true })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(dialog).toBeHidden()
  await expect(page.getByRole('button', { name: 'Ver proyecto Monitoreo remoto' })).toBeFocused()
  await page.getByRole('button', { name: 'Ver proyecto Seguridad para comercios' }).click()
  await page.getByRole('button', { name: 'Consultar por esta solución' }).click()
  await expect(page.getByRole('dialog').filter({ has: page.getByRole('heading', { name: 'Una solución para tu seguridad.' }) })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Una solución para tu seguridad.' })).toBeVisible()
  await page.getByRole('button', { name: 'Cerrar ventana', exact: true }).click()
  expect(errors).toEqual([])
  await page.goto('/')
  await page.evaluate(() => document.fonts.ready)
  await page.screenshot({ path: 'test-results/desktop.png', fullPage: true, animations: 'disabled' })
})

test('contact form saves an inquiry and downloads its copy', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Hablemos', exact: true }).click()
  await page.getByLabel('Tu nombre').fill('María García')
  await page.getByLabel('Tu email').fill('maria@example.com')
  await page.getByLabel('Empresa').fill('Empresa de ejemplo')
  await page.getByRole('dialog').getByRole('button', { name: 'Cámaras web e IP', exact: true }).click()
  await page.getByLabel('Describí tu necesidad').fill('Necesito instalar cámaras para el acceso principal de mi comercio.')
  await page.getByRole('button', { name: 'Enviar mi consulta' }).click()
  await expect(page.getByText('Tu consulta está lista, María.', { exact: false })).toBeVisible()
  await expect(page.getByText('Tu consulta fue enviada y guardada', { exact: false })).toBeVisible()
  const downloadEvent = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Descargar mi consulta' }).click()
  const download = await downloadEvent
  expect(download.suggestedFilename()).toBe('ruben-rodriguez-consulta.txt')
  await download.saveAs('test-results/ruben-rodriguez-consulta.txt')
  const fs = await import('node:fs/promises')
  const content = await fs.readFile('test-results/ruben-rodriguez-consulta.txt', 'utf8')
  expect(content).toContain('María García')
  expect(content).toContain('Servicios: Cámaras web e IP')
  expect(content).toContain('acceso principal')
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toBeHidden()
})

test('mobile menu, modals and layout work at narrow widths', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  const toggle = page.getByRole('button', { name: 'Abrir menú' })
  await toggle.click()
  await expect(page.getByRole('navigation', { name: 'Navegación principal' })).toBeVisible()
  await page.getByRole('navigation', { name: 'Navegación principal' }).getByRole('link', { name: 'Proyectos' }).click()
  await expect(toggle).toHaveAttribute('aria-expanded', 'false')
  await expect(page).toHaveURL(/#proyectos$/)
  await page.getByRole('button', { name: 'Ver proyecto Mantenimiento técnico' }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.getByRole('button', { name: 'Cerrar ventana' }).click()
  for (const width of [320, 390, 768, 1024, 1440]) {
    await page.setViewportSize({ width, height: 900 })
    const overflow = await page.evaluate(() => ({
      fits: document.documentElement.scrollWidth <= window.innerWidth,
      elements: [...document.querySelectorAll('body *')].filter((element) => element.getBoundingClientRect().right > window.innerWidth + 1 && getComputedStyle(element).position !== 'absolute').map((element) => `${element.tagName}.${element.className}`).slice(0, 8),
    }))
    expect(overflow.fits, `no horizontal overflow at ${width}px: ${overflow.elements.join(', ')}`).toBe(true)
  }
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await page.evaluate(() => document.fonts.ready)
  await page.screenshot({ path: 'test-results/mobile.png', fullPage: true, animations: 'disabled' })
})
