import { useEffect, useRef, useState } from 'react'
import { ArrowUpRight, ArrowRight, ArrowDown, Plus, Minus, Menu, X, Code2, Layers3, Cloud, Workflow, Check, Download, MoveUpRight } from 'lucide-react'
import FlowArtwork from './components/FlowArtwork.jsx'
import ProjectVisual from './components/ProjectVisual.jsx'

const services = [
  { number: '01', icon: Code2, title: 'Desarrollo de software', subtitle: 'De una buena idea a un gran producto.', description: 'Aplicaciones web, plataformas y software a medida. Construimos experiencias rápidas, escalables y fáciles de usar, con una base técnica preparada para crecer con tu negocio.', tags: ['Aplicaciones web', 'React & Next.js', 'APIs e integraciones'] },
  { number: '02', icon: Layers3, title: 'Diseño UX/UI', subtitle: 'Experiencias que se sienten naturales.', description: 'Entendemos a tus usuarios y convertimos problemas complejos en experiencias simples. Desde el primer wireframe hasta un sistema de diseño consistente, cada detalle tiene un propósito.', tags: ['Diseño de producto', 'Prototipos', 'Design systems'] },
  { number: '03', icon: Cloud, title: 'Cloud & infraestructura', subtitle: 'Una base sólida para llegar más lejos.', description: 'Diseñamos infraestructura para acompañar la evolución de tu producto. Despliegues automatizados, observabilidad y arquitecturas que priorizan disponibilidad y rendimiento.', tags: ['Cloud', 'DevOps', 'Arquitectura'] },
  { number: '04', icon: Workflow, title: 'Consultoría & automatización', subtitle: 'Menos fricción. Más posibilidades.', description: 'Conectamos herramientas, automatizamos tareas y te ayudamos a tomar decisiones técnicas con claridad. Tecnología aplicada a los desafíos reales de tu operación.', tags: ['Estrategia IT', 'Automatización', 'Integración de sistemas'] },
]

const projects = [
  { id: 'orbit', title: 'Orbit', subtitle: 'Tus finanzas, en otra órbita.', category: 'Desarrollo', type: 'Fintech · Plataforma web', tags: ['Desarrollo web', 'UX/UI'], description: 'Concepto de una plataforma financiera que reúne movimientos, presupuestos y objetivos en una experiencia clara y accesible.', challenge: 'Transformar información financiera compleja en una vista que permita entender y organizar las finanzas de un vistazo.', solution: 'Un dashboard modular con jerarquías visuales claras, gráficos de actividad y una navegación diseñada para simplificar las tareas cotidianas.', stack: ['React', 'TypeScript', 'Design system'] },
  { id: 'nexo', title: 'Nexo', subtitle: 'Una nueva forma de conectar.', category: 'Desarrollo', type: 'E-commerce · Experiencia digital', tags: ['E-commerce', 'Desarrollo web'], description: 'Concepto de una tienda de tecnología donde el producto, la fotografía y una navegación simple comparten el protagonismo.', challenge: 'Crear una experiencia de compra que ayude a descubrir productos sin ruido visual ni pasos innecesarios.', solution: 'Un catálogo editorial, fichas de producto con información ordenada y un recorrido de compra pensado para cualquier pantalla.', stack: ['React', 'E-commerce', 'Responsive design'] },
  { id: 'pulse', title: 'Pulse', subtitle: 'Más tiempo para cuidar.', category: 'Diseño UX/UI', type: 'Healthtech · Diseño de producto', tags: ['Diseño UX/UI', 'Producto digital'], description: 'Concepto de una herramienta de gestión de citas que ayuda a profesionales a organizar su agenda con una interfaz cercana y simple.', challenge: 'Facilitar la lectura de una agenda con múltiples turnos y reducir la carga de tareas administrativas.', solution: 'Un calendario visual con estados reconocibles, vistas diarias y una estructura que da prioridad a la próxima acción.', stack: ['Investigación UX', 'Prototipado', 'Design system'] },
]

function Brand({ footer = false }) {
  return <a className={`brand ${footer ? 'brand-footer' : ''}`} href="#inicio" aria-label="Blackriver, ir al inicio"><svg viewBox="0 0 38 34" fill="none" aria-hidden="true"><path d="M3 7h11c10 0 5 20 19 20M3 17h8c10 0 6-10 15-10h7M3 27h8c10 0 6-10 15-10h7" stroke="currentColor" strokeWidth="4.2" strokeLinecap="round" /></svg><span>blackriver<span className="brand-period">.</span></span></a>
}

function Dialog({ open, onClose, titleId, children, className = '' }) {
  const ref = useRef(null)
  useEffect(() => {
    const dialog = ref.current
    if (!open || !dialog) return
    dialog.showModal()
    const previousOverflow = document.body.style.overflow
    document.body.style.overflow = 'hidden'
    return () => { dialog.close(); document.body.style.overflow = previousOverflow }
  }, [open])
  return <dialog ref={ref} className={`dialog ${className}`} aria-labelledby={titleId} onCancel={onClose} onClick={(event) => { if (event.target === event.currentTarget) { const rect = event.currentTarget.getBoundingClientRect(); if (event.clientX < rect.left || event.clientX > rect.right || event.clientY < rect.top || event.clientY > rect.bottom) onClose() } }}><button className="dialog-close icon-button" aria-label="Cerrar ventana" onClick={onClose}><X size={21} /></button>{children}</dialog>
}

function ContactDialog({ open, onClose }) {
  const [brief, setBrief] = useState(null)
  const [selectedServices, setSelectedServices] = useState([])
  const downloadRef = useRef(null)
  const toggleService = (service) => setSelectedServices((current) => current.includes(service) ? current.filter((item) => item !== service) : [...current, service])
  useEffect(() => { if (brief) downloadRef.current?.focus() }, [brief])
  const handleSubmit = (event) => {
    event.preventDefault()
    const form = event.currentTarget
    const values = Object.fromEntries(new FormData(form))
    const message = form.elements.namedItem('message')
    if (values.message.trim().length < 15) { message.setCustomValidity('Contanos un poco más: escribí al menos 15 caracteres.'); message.reportValidity(); return }
    setBrief({ ...values, services: selectedServices.length ? selectedServices.join(', ') : 'Por definir' })
  }
  const downloadBrief = () => {
    const content = `BLACKRIVER — BRIEF DE PROYECTO\n\nNombre: ${brief.name}\nEmail: ${brief.email}\nEmpresa: ${brief.company || 'Sin especificar'}\nServicios: ${brief.services}\nPresupuesto: ${brief.budget}\n\nLa idea\n${brief.message}\n\nDocumento preparado desde el portafolio de Blackriver. No enviado automáticamente.`
    const url = URL.createObjectURL(new Blob([content], { type: 'text/plain;charset=utf-8' }))
    const link = document.createElement('a')
    link.href = url; link.download = 'blackriver-brief.txt'; link.click()
    setTimeout(() => URL.revokeObjectURL(url), 1000)
  }
  return <Dialog open={open} onClose={onClose} titleId="contact-dialog-title" className="contact-dialog">
    {brief ? <div className="brief-success"><span className="success-icon"><Check size={30} /></span><p className="eyebrow">EL PRIMER PASO ESTÁ DADO</p><h2 id="contact-dialog-title">Las grandes ideas<br />empiezan así<span className="orange">.</span></h2><p>Tu brief está listo, {brief.name.split(' ')[0]}. Descargalo para tener los detalles de tu proyecto a mano.</p><div className="brief-summary"><span>Tu proyecto</span><strong>{brief.services}</strong><p>{brief.message}</p></div><p className="form-note">Esta versión prepara tu brief en el navegador. No se envió ningún mensaje ni se guardaron tus datos en un servidor.</p><button ref={downloadRef} className="button button-orange" onClick={downloadBrief}>Descargar mi brief <Download size={17} /></button><button className="text-button" onClick={() => setBrief(null)}>Preparar otra idea <ArrowRight size={15} /></button></div> : <>
      <p className="eyebrow"><span className="small-dot" /> CONSTRUYAMOS ALGO JUNTOS</p><h2 id="contact-dialog-title">Tu próxima gran idea<br />empieza acá<span className="orange">.</span></h2><p className="dialog-intro">Contanos qué tenés en mente. Vamos a darle forma.</p>
      <form onSubmit={handleSubmit} className="contact-form"><div className="form-row"><label>Tu nombre <span>*</span><input name="name" autoComplete="name" placeholder="¿Cómo te llamás?" required maxLength={100} pattern=".*\S.*" /></label><label>Tu email <span>*</span><input name="email" type="email" autoComplete="email" placeholder="nombre@empresa.com" required maxLength={180} /></label></div><label>Empresa <span className="optional">(opcional)</span><input name="company" autoComplete="organization" placeholder="El nombre de tu empresa" maxLength={150} /></label><fieldset><legend>¿En qué podemos ayudarte?</legend><div className="service-choices">{['Desarrollo', 'Diseño UX/UI', 'Cloud', 'Consultoría'].map((service) => <button key={service} type="button" className={selectedServices.includes(service) ? 'choice selected' : 'choice'} aria-pressed={selectedServices.includes(service)} onClick={() => toggleService(service)}>{service}{selectedServices.includes(service) && <Check size={13} />}</button>)}</div></fieldset><label>Contanos tu idea <span>*</span><textarea name="message" placeholder="Quiero crear una plataforma para..." rows={3} required minLength={15} maxLength={3000} onInput={(event) => event.target.setCustomValidity('')} /></label><label>Presupuesto estimado<select name="budget" defaultValue="Por definir"><option>Por definir</option><option>Menos de USD 5.000</option><option>USD 5.000 – 15.000</option><option>USD 15.000 – 30.000</option><option>Más de USD 30.000</option></select></label><button className="button button-orange form-submit" type="submit">Preparar mi proyecto <ArrowUpRight size={19} /></button><p className="form-note">Generá un brief descargable con tu idea. Los campos con * son obligatorios.</p></form>
    </>}
  </Dialog>
}

function App() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [activeService, setActiveService] = useState(0)
  const [filter, setFilter] = useState('Todos')
  const [selectedProject, setSelectedProject] = useState(null)
  const [contactOpen, setContactOpen] = useState(false)
  const [visible, setVisible] = useState(false)
  const openContact = () => { setSelectedProject(null); setContactOpen(true); setMenuOpen(false) }

  useEffect(() => { const frame = requestAnimationFrame(() => setVisible(true)); return () => cancelAnimationFrame(frame) }, [])
  useEffect(() => {
    if (!menuOpen) return
    const closeOnEscape = (event) => { if (event.key === 'Escape') { setMenuOpen(false); document.querySelector('.menu-toggle')?.focus() } }
    const closeOnResize = () => { if (window.innerWidth > 800) setMenuOpen(false) }
    window.addEventListener('keydown', closeOnEscape)
    window.addEventListener('resize', closeOnResize)
    return () => { window.removeEventListener('keydown', closeOnEscape); window.removeEventListener('resize', closeOnResize) }
  }, [menuOpen])

  return <div className={`site ${visible ? 'is-visible' : ''}`}>
    <a href="#contenido" className="skip-link">Saltar al contenido</a>
    <header className="header"><div className="container nav-container"><Brand /><button className="menu-toggle icon-button" aria-label={menuOpen ? 'Cerrar menú' : 'Abrir menú'} aria-expanded={menuOpen} aria-controls="main-navigation" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X /> : <Menu />}</button><nav className={`navigation ${menuOpen ? 'is-open' : ''}`} id="main-navigation" aria-label="Navegación principal">{[['Servicios', '#servicios'], ['Proyectos', '#proyectos'], ['Nosotros', '#nosotros']].map(([label, href]) => <a key={href} href={href} onClick={() => setMenuOpen(false)}>{label}</a>)}<button className="button button-dark nav-cta" onClick={openContact}>Hablemos <ArrowUpRight size={17} /></button></nav></div></header>
    <main id="contenido">
      <section className="hero container" id="inicio"><div className="hero-copy"><div className="hero-eyebrow"><span className="status-dot" /> TECNOLOGÍA CON DIRECCIÓN.</div><h1>Ideas que <em>fluyen.</em><br />Tecnología que<br /><span className="transform-word">transforma<span className="orange">.</span></span></h1><p className="hero-description">Conectamos estrategia, diseño y desarrollo para<br className="desktop-break" /> crear soluciones digitales que llevan tu negocio<br className="desktop-break" /> al siguiente nivel.</p><div className="hero-actions"><button className="button button-orange" onClick={openContact}>Hablemos de tu proyecto <ArrowUpRight size={19} /></button><a className="text-link" href="#proyectos">Explorá nuestro trabajo <ArrowDown size={16} /></a></div><div className="hero-bottom-note"><span className="tiny-river">↳</span><span>De la primera idea al próximo gran paso.</span></div></div><FlowArtwork /><a className="hero-scroll" href="#servicios" aria-label="Descubrir nuestros servicios"><ArrowDown size={16} /><span>SEGUÍ EXPLORANDO</span></a><div className="hero-index">DISEÑO + CÓDIGO + PROPÓSITO <span>© 2026</span></div></section>
      <section className="stack-strip" aria-label="Tecnologías con las que trabajamos"><div className="container stack-inner"><p>Buenas ideas.<br /><strong>Grandes herramientas.</strong></p><div className="tech-wordmark react-mark"><svg viewBox="-12 -11 24 22" fill="none" aria-hidden="true"><circle r="2" fill="currentColor" />{[0, 60, 120].map((rotate) => <ellipse key={rotate} rx="11" ry="4" stroke="currentColor" strokeWidth="1" transform={`rotate(${rotate})`} />)}</svg>React</div><div className="tech-wordmark next-mark">NEXT<span>.js</span></div><div className="tech-wordmark node-mark">node<span className="node-hex">JS</span></div><div className="tech-wordmark typescript-mark"><span>TS</span>TypeScript</div><div className="tech-wordmark aws-mark">aws<span>⌣</span></div><div className="tech-wordmark figma-mark"><svg viewBox="0 0 18 27" aria-hidden="true"><path d="M4.5 0h9a4.5 4.5 0 0 1 0 9h-9a4.5 4.5 0 0 1 0-9M4.5 9H9v9H4.5a4.5 4.5 0 0 1 0-9M4.5 18H9v4.5a4.5 4.5 0 1 1-4.5-4.5" fill="currentColor" /><circle cx="13.5" cy="13.5" r="4.5" fill="currentColor" /></svg>Figma</div></div></section>
      <section className="services-section section-pad container" id="servicios"><div className="section-heading"><div><p className="eyebrow"><span className="small-dot" /> LO QUE HACEMOS</p><h2>Tu desafío.<br />Nuestro punto de partida<span className="orange">.</span></h2></div><p className="section-description">No creemos en soluciones de molde.<br />Creemos en la tecnología correcta<br />para hacer realidad tu siguiente paso.</p></div><div className="services-layout"><div className="services-statement"><span className="statement-asterisk">✳</span><p>Pensamos con vos.<br />Creamos para<br /><em>lo que viene.</em></p><a href="#contacto" className="text-link">Conozcamos tu idea <ArrowUpRight size={17} /></a><div className="statement-footnote">ESTRATEGIA HUMANA.<br />POTENCIAL DIGITAL.</div></div><div className="service-list">{services.map((service, index) => { const Icon = service.icon; const expanded = activeService === index; return <article className={`service-item ${expanded ? 'expanded' : ''}`} key={service.number}><button className="service-toggle" onClick={() => setActiveService(expanded ? null : index)} aria-expanded={expanded} aria-controls={`service-panel-${index}`} id={`service-button-${index}`}><span className="service-number">{service.number}</span><Icon size={23} strokeWidth={1.5} /><span className="service-title">{service.title}</span><span className="service-expand">{expanded ? <Minus size={18} /> : <Plus size={18} />}</span></button><div id={`service-panel-${index}`} role="region" aria-labelledby={`service-button-${index}`} aria-hidden={!expanded} inert={!expanded} className={`service-panel ${expanded ? 'service-panel--expanded' : 'service-panel--collapsed'}`}><div className="service-panel-inner"><div className="service-panel-content"><p>{service.description}</p><div className="tags">{service.tags.map((tag) => <span key={tag}>{tag}</span>)}</div></div></div></div></article> })}</div></div></section>
      <section className="projects-section section-pad" id="proyectos"><div className="container"><div className="section-heading"><div><p className="eyebrow"><span className="small-dot" /> IDEAS HECHAS EXPERIENCIAS</p><h2>Menos promesas.<br />Más posibilidades<span className="orange">.</span></h2></div><div className="project-heading-aside"><p className="section-description">Una mirada a lo que podemos construir.<br />Explorá nuestros conceptos digitales.</p><div className="project-filters" aria-label="Filtrar proyectos">{['Todos', 'Desarrollo', 'Diseño UX/UI'].map((category) => <button key={category} aria-pressed={filter === category} className={filter === category ? 'filter-button active' : 'filter-button'} onClick={() => setFilter(category)}>{category}</button>)}</div></div></div><div className="project-grid" aria-live="polite">{projects.filter((project) => filter === 'Todos' || project.category === filter).map((project) => <article key={project.id} className="project-card"><div className="project-art-wrap"><ProjectVisual type={project.id} /><span className="project-concept" id={`project-concept-${project.id}`}>PROYECTO CONCEPTUAL</span><span className="project-open" aria-hidden="true"><ArrowUpRight size={24} /></span></div><div className="project-info"><div><span className="project-type" id={`project-type-${project.id}`}>{project.type}</span><h3>{project.title}<span> — {project.subtitle}</span></h3></div><ArrowUpRight size={22} strokeWidth={1.5} aria-hidden="true" /></div><div className="tags project-tags">{project.tags.map((tag) => <span key={tag}>{tag}</span>)}</div><button type="button" className="project-card-button" onClick={() => setSelectedProject(project)} aria-label={`Ver proyecto ${project.title}`} aria-describedby={`project-concept-${project.id} project-type-${project.id}`} aria-haspopup="dialog" /></article>)}</div><div className="projects-foot"><span>Cada proyecto empieza con una conversación.</span><button className="text-link" onClick={openContact}>El próximo puede ser el tuyo <ArrowUpRight size={17} /></button></div></div></section>
      <section className="about-section section-pad container" id="nosotros"><div className="about-art" aria-hidden="true"><div className="about-art-label">BLACKRIVER®<span>HUMAN BY DESIGN.</span></div><div className="river-lines">{Array.from({ length: 11 }, (_, i) => <div key={i} style={{ '--line': i }} />)}</div><div className="about-art-bottom"><span>SIEMPRE EN<br />MOVIMIENTO.</span><ArrowUpRight size={48} strokeWidth={1} /></div></div><div className="about-copy"><p className="eyebrow"><span className="small-dot" /> EL EQUIPO DETRÁS DEL CÓDIGO</p><h2>La tecnología avanza.<br />Hagámoslo <em>juntos.</em></h2><p>Somos Blackriver. Unimos pensamiento estratégico, sensibilidad por el diseño y pasión por la tecnología para resolver problemas que importan.</p><p>Nos involucramos en tu negocio, hablamos tu idioma y trabajamos como parte de tu equipo. Porque las mejores soluciones se construyen de cerca.</p><div className="about-values"><div><span>01 /</span><strong>Personas primero</strong><p>Escuchar, entender y conectar.</p></div><div><span>02 /</span><strong>Calidad en cada detalle</strong><p>Del primer boceto al último commit.</p></div><div><span>03 /</span><strong>Crecer en equipo</strong><p>Tu próximo paso también es el nuestro.</p></div></div></div></section>
      <section className="process-section container"><div className="process-header"><p className="eyebrow">UN CAMINO CLARO, DE PRINCIPIO A FIN</p><h2>Así hacemos que las cosas pasen.</h2></div><div className="process-grid">{[['01', 'Entendemos', 'Escuchamos tu idea, exploramos el problema y definimos una dirección.'], ['02', 'Diseñamos', 'Damos forma a la solución y validamos la experiencia antes de construir.'], ['03', 'Construimos', 'Desarrollamos, probamos y compartimos avances en cada etapa.'], ['04', 'Evolucionamos', 'Lanzamos, aprendemos y acompañamos el siguiente paso de tu producto.']].map(([number, title, text]) => <div className="process-step" key={number}><div className="process-step-top"><span>{number}</span><ArrowRight size={19} /></div><h3>{title}</h3><p>{text}</p></div>)}</div></section>
      <section className="contact-section" id="contacto"><div className="container contact-inner"><div><p className="eyebrow"><span className="small-dot" /> LAS BUENAS IDEAS NO SE QUEDAN QUIETAS</p><h2>¿Y si construimos<br />lo que <em>viene?</em></h2><p>Vos traés la idea. Nosotros, las ganas de hacerla realidad.</p></div><button className="contact-circle" onClick={openContact}><ArrowUpRight size={48} strokeWidth={1.4} /><span>Hablemos de<br />tu proyecto</span></button></div><div className="container contact-bottom"><span><span className="status-dot" /> ABIERTOS A NUEVAS IDEAS</span><span>DE CUALQUIER LUGAR. HACIA ADELANTE.</span></div></section>
    </main>
    <footer className="footer container"><div className="footer-top"><div><Brand footer /><p>Ideas que fluyen. Tecnología que transforma.</p></div><div className="footer-links"><a href="#servicios">Servicios</a><a href="#proyectos">Proyectos</a><a href="#nosotros">Nosotros</a><button onClick={openContact}>Contacto <ArrowUpRight size={14} /></button></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Blackriver. Todos los derechos reservados.</span><span>Hecho con propósito. Y un buen café.</span><a href="#inicio">Volver arriba <MoveUpRight size={14} /></a></div></footer>
    <Dialog open={!!selectedProject} onClose={() => setSelectedProject(null)} titleId="project-dialog-title" className="project-dialog">{selectedProject && <><div className="project-dialog-art"><ProjectVisual type={selectedProject.id} compact /></div><div className="project-dialog-content"><p className="eyebrow">PROYECTO CONCEPTUAL · {selectedProject.type}</p><h2 id="project-dialog-title">{selectedProject.title}<span className="orange">.</span></h2><p className="project-dialog-subtitle">{selectedProject.description}</p><div className="project-detail-grid"><div><h3>El desafío</h3><p>{selectedProject.challenge}</p></div><div><h3>La propuesta</h3><p>{selectedProject.solution}</p></div></div><div className="tags">{selectedProject.stack.map((tag) => <span key={tag}>{tag}</span>)}</div><p className="form-note">Concepto de demostración del portafolio. No representa un cliente ni un proyecto comercial entregado.</p><button className="button button-dark" onClick={openContact}>Quiero construir algo así <ArrowUpRight size={18} /></button></div></>}</Dialog>
    <ContactDialog open={contactOpen} onClose={() => setContactOpen(false)} />
  </div>
}

export default App
